name: Python Package (Conda)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: environment.yml
          python-version: 3.11

      - name: Install dependencies
        run: conda activate myenv && pip install -e .

      - name: Run tests
        run: conda activate myenv && pytest
